/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test void quetesTest ()
   {
      ClassLoader classLoader = getClass().getClassLoader();
      String path = classLoader.getResource("Recentquotes.json").getPath();
      Recentquotes testquet = App.readFile(0,path);
      assertEquals("Recentquotes{author='Marilyn Monroe', text='I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.'}" ,testquet.toString());
   }

   @Test void quetes2Test()
   {
      ClassLoader classLoader = getClass().getClassLoader();
      String path = classLoader.getResource("Recentquotes.json").getPath();
      assertNotNull(App.readFile(0,path));
   }
@Test void quetes3Test ()
{
   ClassLoader classLoader = getClass().getClassLoader();
   String path = classLoader.getResource("Recentquotes.json").getPath();
   Recentquotes testquet = App.readFile(117,path);
   assertEquals("Recentquotes{author='Patrick Ness', text='But the thing about good ideas is that they grow other ideas.'}",testquet.toString());

}
   @Test void quetes4Test ()
   {
      ClassLoader classLoader = getClass().getClassLoader();
      String path = classLoader.getResource("Recentquotes.json").getPath();
      Recentquotes testquet = App.readFile(105,path);
      assertNotEquals("",testquet.toString());
   }
   @Test void quetes5Test()
   {
      ClassLoader classLoader = getClass().getClassLoader();
      String path = classLoader.getResource("Recentquotes.json").getPath();
      Recentquotes testquet = App.readFile(105,path);
      assertEquals("Patrick Ness",testquet.getAuthor());
   }
   @Test void quetes6Test()
   {
      ClassLoader classLoader = getClass().getClassLoader();
      String path = classLoader.getResource("Recentquotes.json").getPath();
      Recentquotes testquet = App.readFile(20,path);
    assertEquals("Can't you find some way of amusing yourself that doesn't involve ringing me up when I'm sleeping?",testquet.getText());
   }

}
