/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;

public class App {

    public static void main(String[] args) throws IOException {

        // prework build the JAVA objects that will hold the JSON data
        // step  1 go to the internet and get the JSON data
        // make a url for the API
        URL qouteUrl = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");

        // making a connection to the API
        HttpURLConnection quoteHttpURLConnection = (HttpURLConnection) qouteUrl.openConnection();

        // specify the method for the connection
        quoteHttpURLConnection.setRequestMethod("GET");

        InputStreamReader qouteInputStreamReader = new InputStreamReader(quoteHttpURLConnection.getInputStream());

        BufferedReader qouteBufferedReader = new BufferedReader(qouteInputStreamReader);
        String qouteData = qouteBufferedReader.readLine();
        System.out.println(qouteData);

        // I got a help to the idea of the next 2 lines (using replace) from my classmate Ala' Alwazani
        qouteData = qouteData.replace("quoteText", "text");
        qouteData = qouteData.replace("quoteAuthor", "author");


        Gson gson = new Gson();
        Recentquotes myQute = gson.fromJson(qouteData, Recentquotes.class);
        System.out.println(myQute);



        // save the response from the API to a file
        File qoutesFile = new File("app/src/main/resources/qoutes.json");
        try (FileWriter qoutesFileWriter = new FileWriter(qoutesFile)) {
            gson.toJson(myQute, qoutesFileWriter);

        }catch(Exception exception )
        {
            int rand = new Random().nextInt(137-0) + 0;
            ClassLoader classLoader = App.class.getClassLoader();
            String path = classLoader.getResource("qoutes.json").getPath();

            System.out.println(readFile(rand, path));
        }

    }



    public static Recentquotes readFile(int num, String path) {
        BufferedReader br = null;
        String strLine = "";
        Recentquotes newQute = null;
        try {
            // create a Gson object
            Gson gson = new Gson();

            // read Gson file
            BufferedReader file = new BufferedReader(new FileReader(path));

            // loop through file until reach null
            while ((strLine = file.readLine()) != null) {
//                System.out.println(strLine);
                Recentquotes[] arrayQuetes = gson.fromJson(file, Recentquotes[].class);
                

//                System.out.println(arrayQuetes.length);
                newQute= arrayQuetes[num];
               String randomQuote = String.valueOf(newQute);

                System.out.println(randomQuote);
                return newQute;
            }
        } catch (IOException exception) {
            System.err.println("An error occurred while trying read a file ");
        }

        return newQute;
    }


    //            int rand = new Random().nextInt(max-min) + min;
}