/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        int rand = new Random().nextInt(137-0) + 0;

        ClassLoader classLoader = App.class.getClassLoader();
        String path = classLoader.getResource("Recentquotes.json").getPath();

        readFile(rand, path);
    }

    public static Recentquotes readFile(int num, String path) {
        BufferedReader br = null;
        String strLine = "";
        Recentquotes newQute = null;
        try {
            // create a Gson object
            Gson gson = new Gson();

            // read Gson file
            BufferedReader file = new BufferedReader(new FileReader(path));

            // loop through file until reach null
            while ((strLine = file.readLine()) != null) {
//                System.out.println(strLine);
                Recentquotes[] arrayQuetes = gson.fromJson(file, Recentquotes[].class);


//                System.out.println(arrayQuetes.length);
                newQute= arrayQuetes[num];
               String randomQuote = String.valueOf(newQute);

                System.out.println(randomQuote);
                return newQute;
            }
        } catch (IOException exception) {
            System.err.println("An error occurred while trying read a file ");
        }

        return newQute;
    }


    //            int rand = new Random().nextInt(max-min) + min;
}